<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="BHANU-LAPTOP" failures="1" tests="2" name="TestLocal" time="16.841" errors="0" timestamp="2022-09-26T09:00:48 IST">
  <testcase classname="script.Test1" name="testA" time="1.812"/>
  <testcase classname="script.Test2" name="testB" time="1.071">
    <failure type="java.lang.AssertionError" message="expected [CONTACT ME] but found [CONTACT US]">
      <![CDATA[java.lang.AssertionError: expected [CONTACT ME] but found [CONTACT US]
at script.Test2.testB(Test2.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase classname="generic.BaseTest" name="@BeforeSuite initReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initReport -->
  <testcase classname="generic.BaseTest" name="@AfterSuite publishReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite publishReport -->
</testsuite> <!-- TestLocal -->
